### ISSUE TITLE
> Task :mokriya_react-native-zoom-us-bridge:compileDebugJavaWithJavac FAILED [BUG]

### ISSUE THREAD

**Issue by SallarBhutto** [mokriya-org/react-native-zoom-us-bridge#19]
Please provide as much details as possible... The more info provided the better

## Description
On react-native run-android  > Task :mokriya_react-native-zoom-us-bridge:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings
12 actionable tasks: 2 executed, 10 up-to-date
/Users/mac/Desktop/E Drive/After May 2020/zoomApp/node_modules/@mokriya/react-native-zoom-us-bridge/android/src/main/java/com/mokriya/zoomus/RNZoomUsBridgeModule.java:128: error: cannot find symbol
        params.zoomToken = zoomToken;
              ^
  symbol:   variable zoomToken
  location: variable params of type StartMeetingParamsWithoutLogin
Note: /Users/mac/Desktop/E Drive/After May 2020/zoomApp/node_modules/@mokriya/react-native-zoom-us-bridge/android/src/main/java/com/mokriya/zoomus/RNZoomUsBridgeModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mokriya_react-native-zoom-us-bridge:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/mac/Desktop/E Drive/After May 2020/zoomApp/node_modules/@mokriya/react-native-zoom-us-bridge/android/src/main/java/com/mokriya/zoomus/RNZoomUsBridgeModule.java:128: error: cannot find symbol

 

## React Native version:
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Memory: 103.55 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 23, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 27.0.3, 28.0.3, 29.0.0, 29.0.2
      System Images: android-19 | Intel x86 Atom, android-19 | Google APIs Intel x86 Atom, android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.5429.30.34.5452501
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_211 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1 
    react-native: 0.63.1 => 0.63.1 
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Configure package manually in android.
2. run react-native run-android

## Expected Results
App should be built and run in debug mode.

**Comment by jimji1005** [comment]
@SallarBhutto thanks for pointing it out, I merged an update to remove userToken from the code base. Zoom SDK 5.0 was updated. Waiting for NPM to update

**Comment by Alessandro1918** [comment]
Hello everyone!

Any news on that update? It seems I´m getting the same error reported above...
(compileDebugJavaWithJavac FAILED)

I filled up the SDK keys, secret, but made no other changes to the example code; don´t know if this zoomSDK.initialize method error is related to this or not.

```
PS C:\Users\Alessandro\Documents\apps\react-native-zoom-us-bridge-master\RNZoomUSBridgeExample> npx react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 896 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...

> Task :mokriya_react-native-zoom-us-bridge:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
27 actionable tasks: 2 executed, 25 up-to-date
C:\Users\Alessandro\Documents\apps\react-native-zoom-us-bridge-master\android\src\main\java\com\mokriya\zoomus\RNZoomUsBridgeModule.java:78: error: method 
initialize in class ZoomSDK cannot be applied to given types;
                zoomSDK.initialize(reactContext.getCurrentActivity(), appKey, appSecret, RNZoomUsBridgeModule.this);
                       ^
  required: Context,ZoomSDKInitializeListener,ZoomSDKInitParams
  found: Activity,String,String,RNZoomUsBridgeModule
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mokriya_react-native-zoom-us-bridge:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.       

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
C:\Users\Alessandro\Documents\apps\react-native-zoom-us-bridge-master\android\src\main\java\com\mokriya\zoomus\RNZoomUsBridgeModule.java:78: error: method 
initialize in class ZoomSDK cannot be applied to given types;
                zoomSDK.initialize(reactContext.getCurrentActivity(), appKey, appSecret, RNZoomUsBridgeModule.this);
                       ^
  required: Context,ZoomSDKInitializeListener,ZoomSDKInitParams
  found: Activity,String,String,RNZoomUsBridgeModule
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mokriya_react-native-zoom-us-bridge:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.       

* Get more help at https://help.gradle.org

BUILD FAILED in 6s

    at makeError (C:\Users\Alessandro\Documents\apps\react-native-zoom-us-bridge-master\RNZoomUSBridgeExample\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at C:\Users\Alessandro\Documents\apps\react-native-zoom-us-bridge-master\RNZoomUSBridgeExample\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (C:\Users\Alessandro\Documents\apps\react-native-zoom-us-bridge-master\RNZoomUSBridgeExample\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\Alessandro\Documents\apps\react-native-zoom-us-bridge-master\RNZoomUSBridgeExample\node_modules\@react-native-community\cli\build\index.js:186:9)
info Run CLI with --verbose flag for more details.

```

Thanks in advance!

**Comment by Hibar3** [comment]
Hi, i ran into this issue as well ever since i updated the Zoom SDK to version 5.7.1 and above. Seems like there are some changes to the data types. i tried fixing the issue on by own by removing that line and append the fix via Android studio suggestion, here's my code snippet 

```
    @ReactMethod
    public void initialize(final ZoomSDKInitializeListener appKey, final ZoomSDKInitParams appSecret, final Promise promise) {
        if (isInitialized) {
        promise.resolve("Already initialize Zoom SDK successfully.");
        return;
        }

        isInitialized = true;

        try {
        initializePromise = promise;

        reactContext.getCurrentActivity().runOnUiThread(new Runnable() {
            @Override
            public void run() {
                ZoomSDK zoomSDK = ZoomSDK.getInstance();

                zoomSDK.initialize(reactContext.getCurrentActivity(), appKey, appSecret);
            }
        });
        } catch (Exception ex) {
        promise.reject("ERR_UNEXPECTED_EXCEPTION", ex);
        }
    }
```

now it throw another error and i'm not sure how to proceed so i downgraded back my SDK to v5.5.1.1317

```
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@usesCleartextTraffic value=(true) from AndroidManifest.xml:7:18-53
  	is also present at [:mobilertc] AndroidManifest.xml:85:9-45 value=(false).
  	Suggestion: add 'tools:replace="android:usesCleartextTraffic"' to <application> element at AndroidManifest.xml:7:5-117 to override.
```

**Comment by anubhavgolu** [comment]
same issue please help me

**Comment by Aayush19** [comment]
>  if (isInitialized) {
>         promise.resolve("Already initialize Zoom SDK successfully.");
>         return;
>         }
> 
>         isInitialized = true;
> 
>         try {
>         initializePromise = promise;
> 
>         reactContext.getCurrentActivity().runOnUiThread(new Runnable() {
>             @Override
>             public void run() {
>                 ZoomSDK zoomSDK = ZoomSDK.getInstance();
> 
>                 zoomSDK.initialize(reactContext.getCurrentActivity(), appKey, appSecret);
>             }
>         });
>         } catch (Exception ex) {
>         promise.reject("ERR_UNEXPECTED_EXCEPTION", ex);
>         }

Hey
just update your android menifest of android/app/src/main/ and android/app/src/debug by adding this lines

android/app/src/debug ==>  <application android:usesCleartextTraffic="false"  tools:replace="android:usesCleartextTraffic" tools:targetApi="28" tools:ignore="GoogleAppIndexingWarning" />

android/app/src/main==> remove android:usesCleartextTraffic="false/true" if mentioned anywhere

**Comment by abhiramareddy20** [comment]
Even Im facing the same issue. > Task :mokriya_react-native-zoom-us-bridge:compileDebugJavaWithJavac FAILED

`error: com.mokriya.zoomus.RNZoomUsBridgeModule is not abstract and does not override abstract method onMeetingParameterNotification(us.zoom.sdk.MeetingParameter) in us.zoom.sdk.MeetingServiceListener
public class RNZoomUsBridgeModule extends ReactContextBaseJavaModule implements ZoomSDKInitializeListener, MeetingServiceListener, LifecycleEventListener {
       ^
error: incompatible types: java.lang.String cannot be converted to us.zoom.sdk.ZoomSDKInitializeListener
                zoomSDK.initialize(reactContext.getCurrentActivity(), appKey, appSecret);
                                                                      ^
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mokriya_react-native-zoom-us-bridge:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

**Comment by kavindadilshan** [comment]
any updates?

**Comment by dishantjaykasodhan-kiwi** [comment]
not fixed

**Comment by yashpyraj** [comment]
A problem occurred configuring project ':@mokriya_react-native-zoom-us-bridge'.
> Configuration with name 'compile' not found.

facing this issue
